name: deploy bot-inspect

on:
  workflow_dispatch:

  push:
    branches:
      - ci/*
      - feat/*
      - fix/*

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: write to wrangler config file
        shell: bash
        run: |
          cd ./
          touch wrangler.jsonc
          echo ${{ secrets.WRANGLER_CONFIG }} > wrangler.jsonc

      - name: test
        shell: bash
        run: |
          npm install
          npm run test

      - name: deploy
        shell: bash
        run: |
          export CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
          npx wrangler deploy > deploy.log && rm deploy.log
